_target_: agent.eval.eval_diffusion_agent.EvalDiffusionAgent
name: can_eval_diffusion_mlp_ta4_td20
logdir: /home/vcj9002/shuyang/robomimic_ckpts/log/robomimic-eval/can_eval_diffusion_mlp_ta4_td20/2026-07-25_20-25-23_42
base_policy_path: /home/vcj9002/shuyang/robomimic_ckpts/log/robomimic/pretrain/can/can_pre_diffusion_mlp_ta4_td20/2024-06-28_13-29-54/checkpoint/state_5000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/can.json
normalization_path: /home/vcj9002/shuyang/robomimic_ckpts/data/robomimic/can/normalization.npz
load_ema: true
seed: 42
device: cuda:3
env_name: can
obs_dim: 23
action_dim: 7
denoising_steps: 20
cond_steps: 1
horizon_steps: 4
act_steps: 4
ft_denoising_steps: 0
n_steps: 300
render_num: 0
env:
  n_envs: 50
  name: can
  best_reward_threshold_for_success: 1
  max_episode_steps: 300
  save_video: false
  wrappers:
    robomimic_lowdim:
      normalization_path: /home/vcj9002/shuyang/robomimic_ckpts/data/robomimic/can/normalization.npz
      low_dim_keys:
      - robot0_eef_pos
      - robot0_eef_quat
      - robot0_gripper_qpos
      - object
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 300
      reset_within_step: true
model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  ft_denoising_steps: 0
  predict_epsilon: true
  denoised_clip_value: 1.0
  randn_clip_value: 3
  network_path: /home/vcj9002/shuyang/robomimic_ckpts/log/robomimic/pretrain/can/can_pre_diffusion_mlp_ta4_td20/2024-06-28_13-29-54/checkpoint/state_5000.pt
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims:
    - 512
    - 512
    - 512
    residual_style: true
    cond_dim: 23
    horizon_steps: 4
    action_dim: 7
  horizon_steps: 4
  obs_dim: 23
  action_dim: 7
  denoising_steps: 20
  device: cuda:3
sim_device: cuda:3
